In [ ]:
from google.colab import files
uploaded = files.upload()

Saving WDICSV.csv to WDICSV.csv

In [ ]:
import pandas as pd
df = pd.read_csv('WDICSV.csv')
df.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Africa Eastern and Southern,AFE,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,18.685118,19.205632,19.742772,20.332679,20.862800,21.419621,21.996456,22.541440,NaN,NaN
1,Africa Eastern and Southern,AFE,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,7.606712,7.926604,8.309896,8.704591,9.106640,9.480804,9.903209,10.288154,NaN,NaN
2,Africa Eastern and Southern,AFE,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,39.052626,39.321068,39.649534,39.968299,40.354628,40.723805,41.026351,41.289974,NaN,NaN
3,Africa Eastern and Southern,AFE,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,38.859598,40.223744,43.035073,44.390861,46.282371,48.127211,48.801258,50.667516,NaN,NaN
4,Africa Eastern and Southern,AFE,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,24.584906,25.375037,26.941984,28.983183,30.909991,32.709837,33.747222,35.240236,NaN,NaN

In [ ]:
df.isnull().sum()

Country Name           0
Country Code           0
Indicator Name         0
Indicator Code         0
1960              357867
                   ...
2021              186312
2022              201015
2023              217962
2024              256760
2025              372673
Length: 70, dtype: int64

In [ ]:
df.dtypes

Country Name       object
Country Code       object
Indicator Name     object
Indicator Code     object
1960              float64
                   ...
2021              float64
2022              float64
2023              float64
2024              float64
2025              float64
Length: 70, dtype: object

In [ ]:
for indicator in sorted (df["Indicator Name"].unique()):
  print(indicator)

ARI treatment (% of children under 5 taken to a health provider)
Access to clean fuels and technologies for cooking (% of population)
Access to clean fuels and technologies for cooking, rural (% of rural population)
Access to clean fuels and technologies for cooking, urban (% of urban population)
Access to electricity (% of population)
Access to electricity, rural (% of rural population)
Access to electricity, urban (% of urban population)
Account ownership at a financial institution or with a mobile-money-service provider (% of population ages 15+)
Account ownership at a financial institution or with a mobile-money-service provider, female (% of population ages 15+)
Account ownership at a financial institution or with a mobile-money-service provider, male (% of population ages 15+)
Account ownership at a financial institution or with a mobile-money-service provider, older adults (% of population ages 25+)
Account ownership at a financial institution or with a mobile-money-service provider, poorest 40% (% of population ages 15+)
Account ownership at a financial institution or with a mobile-money-service provider, primary education or less (% of population ages 15+)
Account ownership at a financial institution or with a mobile-money-service provider, richest 60% (% of population ages 15+)
Account ownership at a financial institution or with a mobile-money-service provider, secondary education or more (% of population ages 15+)
Account ownership at a financial institution or with a mobile-money-service provider, young adults (% of population ages 15-24)
Adequacy of social insurance programs (% of total welfare of beneficiary households)
Adequacy of social protection and labor programs (% of total welfare of beneficiary households)
Adequacy of social safety net programs (% of total welfare of beneficiary households)
Adequacy of unemployment benefits and ALMP (% of total welfare of beneficiary households)
Adjusted net enrollment rate, primary (% of primary school age children)
Adjusted net enrollment rate, primary, female (% of primary school age children)
Adjusted net enrollment rate, primary, male (% of primary school age children)
Adjusted net national income (annual % growth)
Adjusted net national income (constant 2015 US$)
Adjusted net national income (current US$)
Adjusted net national income per capita (annual % growth)
Adjusted net national income per capita (constant 2015 US$)
Adjusted net national income per capita (current US$)
Adjusted net savings, excluding particulate emission damage (% of GNI)
Adjusted net savings, excluding particulate emission damage (current US$)
Adjusted net savings, including particulate emission damage (% of GNI)
Adjusted net savings, including particulate emission damage (current US$)
Adjusted savings: carbon dioxide damage (% of GNI)
Adjusted savings: carbon dioxide damage (current US$)
Adjusted savings: consumption of fixed capital (% of GNI)
Adjusted savings: consumption of fixed capital (current US$)
Adjusted savings: education expenditure (% of GNI)
Adjusted savings: education expenditure (current US$)
Adjusted savings: energy depletion (% of GNI)
Adjusted savings: energy depletion (current US$)
Adjusted savings: gross savings (% of GNI)
Adjusted savings: mineral depletion (% of GNI)
Adjusted savings: mineral depletion (current US$)
Adjusted savings: natural resources depletion (% of GNI)
Adjusted savings: net forest depletion (% of GNI)
Adjusted savings: net forest depletion (current US$)
Adjusted savings: net national savings (% of GNI)
Adjusted savings: net national savings (current US$)
Adjusted savings: particulate emission damage (% of GNI)
Adjusted savings: particulate emission damage (current US$)
Adolescent fertility rate (births per 1,000 women ages 15-19)
Adolescents out of school (% of lower secondary school age)
Adolescents out of school, female (% of female lower secondary school age)
Adolescents out of school, male (% of male lower secondary school age)
Adults (ages 15+) and children (ages 0-14) newly infected with HIV
Adults (ages 15-49) newly infected with HIV
Age dependency ratio (% of working-age population)
Age dependency ratio, old (% of working-age population)
Age dependency ratio, young (% of working-age population)
Agricultural irrigated land (% of total agricultural land)
Agricultural land (% of land area)
Agricultural land (sq. km)
Agricultural raw materials exports (% of merchandise exports)
Agricultural raw materials imports (% of merchandise imports)
Agriculture, forestry, and fishing, value added (% of GDP)
Agriculture, forestry, and fishing, value added (annual % growth)
Agriculture, forestry, and fishing, value added (constant 2015 US$)
Agriculture, forestry, and fishing, value added (constant LCU)
Agriculture, forestry, and fishing, value added (current LCU)
Agriculture, forestry, and fishing, value added (current US$)
Agriculture, forestry, and fishing, value added per worker (constant 2015 US$)
Air transport, freight (million ton-km)
Air transport, passengers carried
Air transport, registered carrier departures worldwide
Alternative and nuclear energy (% of total energy use)
Annual freshwater withdrawals, agriculture (% of total freshwater withdrawal)
Annual freshwater withdrawals, domestic (% of total freshwater withdrawal)
Annual freshwater withdrawals, industry (% of total freshwater withdrawal)
Annual freshwater withdrawals, total (% of internal resources)
Annual freshwater withdrawals, total (billion cubic meters)
Annualized average growth rate in per capita real survey mean consumption or income, bottom 40% of population (%)
Annualized average growth rate in per capita real survey mean consumption or income, total population (%)
Antiretroviral therapy coverage (% of people living with HIV)
Antiretroviral therapy coverage for PMTCT (% of pregnant women living with HIV)
Aquaculture production (metric tons)
Arable land (% of land area)
Arable land (hectares per person)
Arable land (hectares)
Armed forces personnel (% of total labor force)
Armed forces personnel, total
Arms exports (SIPRI trend indicator values)
Arms imports (SIPRI trend indicator values)
Asylum-seekers by country or territory of asylum
Asylum-seekers by country or territory of origin
Automated teller machines (ATMs) (per 100,000 adults)
Average precipitation in depth (mm per year)
Average time to clear exports through customs (days)
Average time to clear imports through customs (days)
Average transaction cost of sending remittances from a specific country (%)
Average transaction cost of sending remittances to a specific country (%)
Average working hours of children, study and work, ages 7-14 (hours per week)
Average working hours of children, study and work, female, ages 7-14 (hours per week)
Average working hours of children, study and work, male, ages 7-14 (hours per week)
Average working hours of children, working only, ages 7-14 (hours per week)
Average working hours of children, working only, female, ages 7-14 (hours per week)
Average working hours of children, working only, male, ages 7-14 (hours per week)
B-READY: Business Entry Pillar 1: Quality of Regulations for Business Entry
B-READY: Business Entry Pillar 2: Digital Public Services and Transparency of Information for Business Entry
B-READY: Business Entry Pillar 3: Operational Efficiency of Business Entry
B-READY: Business Entry: Overall Score
B-READY: Business Insolvency Pillar 1: Quality of Regulations for Judicial Insolvency Proceedings
B-READY: Business Insolvency Pillar 2: Quality of Institutional and Operational Infrastructure for Judicial Insolvency Proceedings
B-READY: Business Insolvency Pillar 3: Operational Efficiency of Resolving Judicial Insolvency Proceedings
B-READY: Business Insolvency: Overall Score
B-READY: Business Location Pillar 1: Quality of Regulations for Business Location
B-READY: Business Location Pillar 2: Quality of Public Services and Transparency of Information for Business Location
B-READY: Business Location Pillar 3: Operational Efficiency of Establishing a Business Location
B-READY: Business Location: Overall Score
B-READY: Dispute Resolution Pillar 1: Quality of Regulations for Dispute Resolution
B-READY: Dispute Resolution Pillar 2: Public Services for Dispute Resolution
B-READY: Dispute Resolution Pillar 3:  Ease of Resolving a Commercial Dispute
B-READY: Dispute Resolution: Overall Score
B-READY: Financial Services Pillar 1: Quality of Regulations for Financial Services
B-READY: Financial Services Pillar 2: Accessibility of Information in Credit Infrastructure
B-READY: Financial Services Pillar 3: Operational Efficiency of Receiving Financial Services
B-READY: Financial Services: Overall Score
B-READY: International Trade Pillar 1: Quality of Regulations for International Trade
B-READY: International Trade Pillar 2: Quality of Public Services for the Facilitation of International Trade
B-READY: International Trade Pillar 3: Efficiency of Importing Goods, Exporting Goods, and Engaging in Digital Trade
B-READY: International Trade: Overall Score
B-READY: Labor Pillar 1: Quality of Labor Regulations
B-READY: Labor Pillar 2: Adequacy of Public Services for Labor
B-READY: Labor Pillar 3: Operational Efficiency of Labor Regulations and Public Services in Practice
B-READY: Labor: Overall Score
B-READY: Market Competition Pillar 1: Quality of Regulations that Promote Market Competition
B-READY: Market Competition Pillar 2: Public Services that Promote Market Competition
B-READY: Market Competition Pillar 3:  Implementation of Key Services Promoting Market Competition
B-READY: Market Competition: Overall Score
B-READY: Pillar 1: Regulatory Framework
B-READY: Pillar 2: Public Services
B-READY: Pillar 3: Operational Efficiency
B-READY: Taxation Pillar 1: Quality of Regulations on Taxation
B-READY: Taxation Pillar 2: Public Services Provided by the Tax Administration
B-READY: Taxation Pillar 3: Operational Efficiency of Tax Systems in Practice
B-READY: Taxation: Overall Score
B-READY: Utility Services Pillar 1: Quality of Regulations on Utility Services
B-READY: Utility Services Pillar 2: Quality of Governance and Transparency of Utility Services
B-READY: Utility Services Pillar 3: Operational Efficiency of Utility Service Provision
B-READY: Utility Services: Overall Score
Bank capital to assets ratio (%)
Bank liquid reserves to bank assets ratio (%)
Bank nonperforming loans to total gross loans (%)
Battle-related deaths (number of people)
Benefit incidence of social insurance programs to poorest quintile (% of total social insurance benefits)
Benefit incidence of social protection and labor programs to poorest quintile (% of total SPL benefits)
Benefit incidence of social safety net programs to poorest quintile (% of total safety net benefits)
Benefit incidence of unemployment benefits and ALMP to poorest quintile (% of total U/ALMP benefits)
Binding coverage, all products (%)
Binding coverage, manufactured products (%)
Binding coverage, primary products (%)
Bird species, threatened
Birth rate, crude (per 1,000 people)
Births attended by skilled health staff (% of total)
Borrowers from commercial banks (per 1,000 adults)
Bound rate, simple mean, all products (%)
Bound rate, simple mean, manufactured products (%)
Bound rate, simple mean, primary products (%)
Bribery incidence (% of firms experiencing at least one bribe payment request)
Broad money (% of GDP)
Broad money (current LCU)
Broad money growth (annual %)
Broad money to total reserves ratio
CPIA building human resources rating (1=low to 6=high)
CPIA business regulatory environment rating (1=low to 6=high)
CPIA debt policy rating (1=low to 6=high)
CPIA economic management cluster average (1=low to 6=high)
CPIA efficiency of revenue mobilization rating (1=low to 6=high)
CPIA equity of public resource use rating (1=low to 6=high)
CPIA financial sector rating (1=low to 6=high)
CPIA fiscal policy rating (1=low to 6=high)
CPIA gender equality rating (1=low to 6=high)
CPIA macroeconomic management rating (1=low to 6=high)
CPIA policies for social inclusion/equity cluster average (1=low to 6=high)
CPIA policy and institutions for environmental sustainability rating (1=low to 6=high)
CPIA property rights and rule-based governance rating (1=low to 6=high)
CPIA public sector management and institutions cluster average (1=low to 6=high)
CPIA quality of budgetary and financial management rating (1=low to 6=high)
CPIA quality of public administration rating (1=low to 6=high)
CPIA social protection rating (1=low to 6=high)
CPIA structural policies cluster average (1=low to 6=high)
CPIA trade rating (1=low to 6=high)
CPIA transparency, accountability, and corruption in the public sector rating (1=low to 6=high)
Capture fisheries production (metric tons)
Carbon dioxide (CO2) emissions (total) excluding LULUCF (% change from 1990)
Carbon dioxide (CO2) emissions (total) excluding LULUCF (Mt CO2e)
Carbon dioxide (CO2) emissions excluding LULUCF per capita (t CO2e/capita)
Carbon dioxide (CO2) emissions from Agriculture (Mt CO2e)
Carbon dioxide (CO2) emissions from Building (Energy) (Mt CO2e)
Carbon dioxide (CO2) emissions from Fugitive Emissions (Energy) (Mt CO2e)
Carbon dioxide (CO2) emissions from Industrial Combustion (Energy) (Mt CO2e)
Carbon dioxide (CO2) emissions from Industrial Processes (Mt CO2e)
Carbon dioxide (CO2) emissions from Power Industry (Energy) (Mt CO2e)
Carbon dioxide (CO2) emissions from Transport (Energy) (Mt CO2e)
Carbon dioxide (CO2) emissions from Waste (Mt CO2e)
Carbon dioxide (CO2) net fluxes from LULUCF - Deforestation (Mt CO2e)
Carbon dioxide (CO2) net fluxes from LULUCF - Forest Land (Mt CO2e)
Carbon dioxide (CO2) net fluxes from LULUCF - Organic Soil (Mt CO2e)
Carbon dioxide (CO2) net fluxes from LULUCF - Other Land (Mt CO2e)
Carbon dioxide (CO2) net fluxes from LULUCF - Total excluding non-tropical fires (Mt CO2e)
Carbon intensity of GDP (kg CO2e per 2021 PPP $ of GDP)
Carbon intensity of GDP (kg CO2e per constant 2015 US$ of GDP)
Cause of death, by communicable diseases and maternal, prenatal and nutrition conditions (% of total)
Cause of death, by injury (% of total)
Cause of death, by non-communicable diseases (% of total)
Cause of death, by other COVID-19 pandemic-related outcomes (% of total)
Central government debt, total (% of GDP)
Central government debt, total (current LCU)
Cereal production (metric tons)
Cereal yield (kg per hectare)
Changes in inventories (constant LCU)
Changes in inventories (current LCU)
Changes in inventories (current US$)
Charges for the use of intellectual property, payments (BoP, current US$)
Charges for the use of intellectual property, receipts (BoP, current US$)
Chemicals (% of value added in manufacturing)
Child employment in agriculture (% of economically active children ages 7-14)
Child employment in agriculture, female (% of female economically active children ages 7-14)
Child employment in agriculture, male (% of male economically active children ages 7-14)
Child employment in manufacturing (% of economically active children ages 7-14)
Child employment in manufacturing, female (% of female economically active children ages 7-14)
Child employment in manufacturing, male (% of male economically active children ages 7-14)
Child employment in services (% of economically active children ages 7-14)
Child employment in services, female (% of female economically active children ages 7-14)
Child employment in services, male (% of male economically active children ages 7-14)
Children (0-14) living with HIV
Children (ages 0-14) newly infected with HIV
Children in employment, female (% of female children ages 7-14)
Children in employment, male (% of male children ages 7-14)
Children in employment, self-employed (% of children in employment, ages 7-14)
Children in employment, self-employed, female (% of female children in employment, ages 7-14)
Children in employment, self-employed, male (% of male children in employment, ages 7-14)
Children in employment, study and work (% of children in employment, ages 7-14)
Children in employment, study and work, female (% of female children in employment, ages 7-14)
Children in employment, study and work, male (% of male children in employment, ages 7-14)
Children in employment, total (% of children ages 7-14)
Children in employment, unpaid family workers (% of children in employment, ages 7-14)
Children in employment, unpaid family workers, female (% of female children in employment, ages 7-14)
Children in employment, unpaid family workers, male (% of male children in employment, ages 7-14)
Children in employment, wage workers (% of children in employment, ages 7-14)
Children in employment, wage workers, female (% of female children in employment, ages 7-14)
Children in employment, wage workers, male (% of male children in employment, ages 7-14)
Children in employment, work only (% of children in employment, ages 7-14)
Children in employment, work only, female (% of female children in employment, ages 7-14)
Children in employment, work only, male (% of male children in employment, ages 7-14)
Children out of school (% of primary school age)
Children out of school, female (% of female primary school age)
Children out of school, male (% of male primary school age)
Children out of school, primary
Children out of school, primary, female
Children out of school, primary, male
Children with fever receiving antimalarial drugs (% of children under age 5 with fever)
Claims on central government (annual growth as % of broad money)
Claims on central government, etc. (% GDP)
Claims on other sectors of the domestic economy (% of GDP)
Claims on other sectors of the domestic economy (annual growth as % of broad money)
Claims on private sector (annual growth as % of broad money)
Coal rents (% of GDP)
Combustible renewables and waste (% of total energy)
Commercial bank branches (per 100,000 adults)
Commercial banks and other lending (PPG + PNG) (NFL, current US$)
Commercial service exports (current US$)
Commercial service imports (current US$)
Communications, computer, etc. (% of service exports, BoP)
Communications, computer, etc. (% of service imports, BoP)
Community health workers (per 1,000 people)
Compensation of employees (% of expense)
Compensation of employees (current LCU)
Completeness of birth registration (%)
Completeness of birth registration, female (%)
Completeness of birth registration, male (%)
Completeness of birth registration, rural (%)
Completeness of birth registration, urban (%)
Completeness of death registration with cause-of-death information (%)
Compulsory education, duration (years)
Computer, communications and other services (% of commercial service exports)
Computer, communications and other services (% of commercial service imports)
Condom use, population ages 15-24, female (% of females ages 15-24)
Condom use, population ages 15-24, male (% of males ages 15-24)
Consumer price index (2010 = 100)
Consumption of iodized salt (% of households)
Container port traffic (TEU: 20 foot equivalent units)
Contraceptive prevalence, any method (% of married women ages 15-49)
Contraceptive prevalence, any modern method (% of married women ages 15-49)
Contributing family workers, female (% of female employment) (modeled ILO estimate)
Contributing family workers, male (% of male employment) (modeled ILO estimate)
Contributing family workers, total (% of total employment) (modeled ILO estimate)
Coverage of social insurance programs (% of population)
Coverage of social insurance programs in 2nd quintile (% of population)
Coverage of social insurance programs in 3rd quintile (% of population)
Coverage of social insurance programs in 4th quintile (% of population)
Coverage of social insurance programs in poorest quintile (% of population)
Coverage of social insurance programs in richest quintile (% of population)
Coverage of social protection and labor programs (% of population)
Coverage of social safety net programs (% of population)

In [ ]:
#indicators i want to use for my analysis
indicators = [
    "GDP growth (annual %)",
    "GDP per capita (current US$)",
    "Labor force participation rate, total (% of total population ages 15+) (modeled ILO estimate)",
    "Unemployment, total (% of total labor force) (modeled ILO estimate)",
    "Employment to population ratio, 15+, total (%) (modeled ILO estimate)",
    "Inflation, consumer prices (annual %)",
    "Population, total"
]

In [ ]:

df[df["Indicator Name"].isin(indicators)]

,Country Name,Country Code,Indicator Name,Indicator Code,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
404,Africa Eastern and Southern,AFE,"Employment to population ratio, 15+, total (%)...",SL.EMP.TOTL.SP.ZS,6.506705e+01,6.528401e+01,6.470469e+01,6.551668e+01,6.473830e+01,6.433509e+01,6.376758e+01,6.306175e+01,6.263082e+01,6.209258e+01,6.069385e+01,6.048173e+01,6.117237e+01,6.359664e+01,6.366151e+01
512,Africa Eastern and Southern,AFE,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,5.307904e+00,4.077477e+00,1.897173e+00,4.356682e+00,3.920390e+00,2.934030e+00,2.130117e+00,2.677524e+00,2.705194e+00,2.030077e+00,-2.817572e+00,4.578772e+00,3.722717e+00,1.931160e+00,2.763839e+00
516,Africa Eastern and Southern,AFE,GDP per capita (current US$),NY.GDP.PCAP.CD,1.628905e+03,1.761989e+03,1.732038e+03,1.706023e+03,1.690167e+03,1.498875e+03,1.334471e+03,1.528104e+03,1.552074e+03,1.507086e+03,1.351592e+03,1.562416e+03,1.679328e+03,1.571449e+03,1.615396e+03
670,Africa Eastern and Southern,AFE,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,5.537538e+00,8.971206e+00,9.158708e+00,5.748831e+00,5.525819e+00,5.098562e+00,6.446877e+00,6.221375e+00,4.689806e+00,4.102851e+00,5.191629e+00,6.824727e+00,1.088348e+01,7.399186e+00,4.770857e+00
716,Africa Eastern and Southern,AFE,"Labor force participation rate, total (% of to...",SL.TLF.CACT.ZS,7.022100e+01,7.042749e+01,6.965633e+01,7.036472e+01,6.950847e+01,6.912626e+01,6.862216e+01,6.796529e+01,6.752271e+01,6.709728e+01,6.595311e+01,6.603366e+01,6.639743e+01,6.888437e+01,6.887659e+01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394306,Zimbabwe,ZWE,GDP per capita (current US$),NY.GDP.PCAP.CD,9.020108e+02,1.037776e+03,1.239227e+03,1.362995e+03,1.372915e+03,1.387126e+03,1.408139e+03,3.445449e+03,2.270895e+03,2.184329e+03,2.059674e+03,2.613605e+03,2.536401e+03,2.195225e+03,2.497203e+03
394460,Zimbabwe,ZWE,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,3.022670e+00,3.466130e+00,3.725327e+00,1.634950e+00,-1.977848e-01,-2.430968e+00,-1.543670e+00,8.939623e-01,1.061887e+01,2.553050e+02,5.572018e+02,9.854611e+01,1.047052e+02,0.000000e+00,0.000000e+00
394506,Zimbabwe,ZWE,"Labor force participation rate, total (% of to...",SL.TLF.CACT.ZS,6.592500e+01,6.601300e+01,6.609200e+01,6.614800e+01,6.615800e+01,6.613000e+01,6.607000e+01,6.598900e+01,6.589400e+01,6.579500e+01,6.466500e+01,6.539700e+01,6.521400e+01,6.778600e+01,6.772500e+01
394909,Zimbabwe,ZWE,"Population, total",SP.POP.TOTL,1.335655e+07,1.359542e+07,1.381789e+07,1.401381e+07,1.420736e+07,1.439901e+07,1.460029e+07,1.481248e+07,1.503445e+07,1.527137e+07,1.552689e+07,1.579721e+07,1.606906e+07,1.634082e+07,1.663437e+07
395232,Zimbabwe,ZWE,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,5.469000e+00,5.368000e+00,5.057000e+00,4.948000e+00,4.774000e+00,5.399000e+00,5.896000e+00,6.350000e+00,6.788000e+00,7.373000e+00,8.617000e+00,9.540000e+00,1.008700e+01,9.348000e+00,9.435000e+00

In [ ]:
#years of analyzes (2010-2024)
years = [str(year) for year in range (2010, 2025)]

In [ ]:
#columns and rows needed for analysis
df = df[df["Indicator Name"].isin(indicators)]

columns_to_keep = [
    "Country Name",
    "Country Code",
    "Indicator Name",
    "Indicator Code"
] + years

df = df[columns_to_keep]

In [ ]:
#changing year columns per year to row
df_long = df.melt(
    id_vars=['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code'],
    var_name='Year',
    value_name='Value'
)
print("Long Format:")
print(df_long.head())

Long Format:
                  Country Name Country Code  \
0  Africa Eastern and Southern          AFE
1  Africa Eastern and Southern          AFE
2  Africa Eastern and Southern          AFE
3  Africa Eastern and Southern          AFE
4  Africa Eastern and Southern          AFE

                                      Indicator Name     Indicator Code  Year  \
0  Employment to population ratio, 15+, total (%)...  SL.EMP.TOTL.SP.ZS  2010
1                              GDP growth (annual %)  NY.GDP.MKTP.KD.ZG  2010
2                       GDP per capita (current US$)     NY.GDP.PCAP.CD  2010
3              Inflation, consumer prices (annual %)     FP.CPI.TOTL.ZG  2010
4  Labor force participation rate, total (% of to...     SL.TLF.CACT.ZS  2010

         Value
0    65.067051
1     5.307904
2  1628.905248
3     5.537538
4    70.221003

In [ ]:
df.isnull().sum()

Country Name        0
Country Code        0
Indicator Name      0
Indicator Code      0
2010              183
2011              178
2012              182
2013              183
2014              181
2015              182
2016              184
2017              189
2018              189
2019              190
2020              196
2021              196
2022              201
2023              221
2024              250
dtype: int64

In [ ]:
df.fillna(0, inplace=True)
print(df.isnull().sum())

Country Name      0
Country Code      0
Indicator Name    0
Indicator Code    0
2010              0
2011              0
2012              0
2013              0
2014              0
2015              0
2016              0
2017              0
2018              0
2019              0
2020              0
2021              0
2022              0
2023              0
2024              0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
print(df.shape)

(1862, 19)

In [ ]:
df_long.to_csv("WDI_cleaned_data.csv", index=False)